---
title: "fsh556 Notes"
author: "Dan Ovando"
date: "3/27/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE, message = FALSE, warning = FALSE)
library(TMB)
library(tidyverse)


```

# lecture 1

second derivative informs whether a minimum is a "true" global minimum, first derivative for local minima. 

## why maximum likelihood ?

You can transform parameters and still end up with the same likelihood profile, which is not necessarily true of Bayesian models

consistent in the limit

asymptotic normality


# lab 1

poisson, number of people that hit a website in a given time

decay of radioactive material 

newton was the first optimizer! quasi newton methods, optimize by second derivatives

nelder-mead is like a little aomeba that searches around with a different leg for each parameter and just hunts aroung. With TMB, you pass a gradient to nelder-mead

check that hessian matrix is positive definite



# lecture-2

we like consistency (will converge to the best estimate of the correct model or the best for the mispecified model) and asymptotic normality 

why is stein's paradox a paradox? you'd expecte the mean for each person to be the best predictor for that person, rather than a better predictor is that person with some shrinkage towards the mean

w in shrinkage slides is precision, or inverse variance

residual variance in lme4 is the variance of the error term in a linear model

A full rank matrix every eigen value of the matrix is greater than zero. If it is rank deficient then one or more eigen values will be basically zero. We need full rank for laplace approximation

Rank of a matrix is the number of linearaly independent columns in a matrix

Lapalce approximation fails if one or more matrices is rank deficient. 

Standard errors will also fail if one matrix is rank deficient 

If you estimate the model and that works but the standard errors fail, then its fixed effects problem, if it fails in the fitting stage, the problem may be in the random effect

Why treat "study" as a random effect? Might have very little data for any one individual study, so random effect might help. Hierarchichal model gives you what you might actually want which is the mean effect across the the effects. 

TO invert a matrix you need it to be full rank. So, if the hessian is no rank, then you can't invert it, so you can't get the standard errors


# lecture 3 - kalman filters

one state space definition - the latent variable has a time series process, with some markovian process

consistency in time series models. two forms of consistency in time series. If you add more data within your model period, infill asymptotics, and if you add more time periods but the same number of data points per time periods thats sprawl asymptotics. There are two different implications of these two things

REML - restricted maximum likelihood

there's no guarantee that maximum likelihood is unbiased for a finite sample size

e.g. variance. If you look at th maximum likelihood estimate of the variance for a linear model, it will just be the average squared deviation. Gets shrunk to the mean of the data and not the "true" value. 

use REML to treat non-variance fixed effects as random, not entirely sure why


# lab 3

gompertz model. Growth rate goes to infinity at the extreme

alpha over beta is the carrying capacity

look up stochastic SRA

autoregreesive term, it's the simplist biological model that is identical to a linear model

sigma here is a process error

when rho is negative in an autoregressive model you teh osscilation

map function in TMB

the mpa input has two basic roles, one is turning off a parameter, and the other is mirroring a parameter, or making some set of parameters in in the model all equal. 

e.g. comparing a mixed effects model to a pure linear model. 

map in this way basically fixes things at starting values, it's not actually setting things to NA?

NA turns off, a level sets a initial value?

reminder on inner and outer optimizer

inner is the lapace approximation solving the random effects holding the fixed effects constant. Given the value of fixed effects, optimize random effects, do lapace approximation. 

Then, the outer loop is holding the random effects constant, and then optimizing the fixed effects

in the pollock example, sigma b is the process error

of process and observation error are independent, then variances should be additivie

standard error is just the standard deviation between your samples n divided by the square root of n if all n are independent

the claim is that we can estimate the standard error around the mean from the variance of the sampling. 

Need to calculate the standard error for the index and convert to the standard error of a log-normal file